# Generated by Django 4.2 on 2023-05-27 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='data_aluguel',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
