# Generated by Django 4.2 on 2023-05-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_alter_aluguel_data_aluguel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='devolucao',
            field=models.BooleanField(default=True),
        ),
    ]
