# Generated by Django 4.2 on 2023-05-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('fabricante', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
